// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_main is a generated GoMock package.
package mock_main

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockProcessingContextInterface is a mock of ProcessingContextInterface interface
type MockProcessingContextInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProcessingContextInterfaceMockRecorder
}

// MockProcessingContextInterfaceMockRecorder is the mock recorder for MockProcessingContextInterface
type MockProcessingContextInterfaceMockRecorder struct {
	mock *MockProcessingContextInterface
}

// NewMockProcessingContextInterface creates a new mock instance
func NewMockProcessingContextInterface(ctrl *gomock.Controller) *MockProcessingContextInterface {
	mock := &MockProcessingContextInterface{ctrl: ctrl}
	mock.recorder = &MockProcessingContextInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProcessingContextInterface) EXPECT() *MockProcessingContextInterfaceMockRecorder {
	return m.recorder
}

// AddProcessingFile mocks base method
func (m *MockProcessingContextInterface) AddProcessingFile(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProcessingFile", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProcessingFile indicates an expected call of AddProcessingFile
func (mr *MockProcessingContextInterfaceMockRecorder) AddProcessingFile(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProcessingFile", reflect.TypeOf((*MockProcessingContextInterface)(nil).AddProcessingFile), name)
}

// CurrentlyProcessing mocks base method
func (m *MockProcessingContextInterface) CurrentlyProcessing(name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentlyProcessing", name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentlyProcessing indicates an expected call of CurrentlyProcessing
func (mr *MockProcessingContextInterfaceMockRecorder) CurrentlyProcessing(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentlyProcessing", reflect.TypeOf((*MockProcessingContextInterface)(nil).CurrentlyProcessing), name)
}
