// Code generated by MockGen. DO NOT EDIT.
// Source: processingcontext.go

// Package mock_main is a generated GoMock package.
package mock_main

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockProcessingContextInterface is a mock of ProcessingContextInterface interface
type MockProcessingContextInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProcessingContextInterfaceMockRecorder
}

// MockProcessingContextInterfaceMockRecorder is the mock recorder for MockProcessingContextInterface
type MockProcessingContextInterfaceMockRecorder struct {
	mock *MockProcessingContextInterface
}

// NewMockProcessingContextInterface creates a new mock instance
func NewMockProcessingContextInterface(ctrl *gomock.Controller) *MockProcessingContextInterface {
	mock := &MockProcessingContextInterface{ctrl: ctrl}
	mock.recorder = &MockProcessingContextInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProcessingContextInterface) EXPECT() *MockProcessingContextInterfaceMockRecorder {
	return m.recorder
}

// AddProcessingFile mocks base method
func (m *MockProcessingContextInterface) AddProcessingFile(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProcessingFile", name)
}

// AddProcessingFile indicates an expected call of AddProcessingFile
func (mr *MockProcessingContextInterfaceMockRecorder) AddProcessingFile(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProcessingFile", reflect.TypeOf((*MockProcessingContextInterface)(nil).AddProcessingFile), name)
}

// CurrentlyProcessing mocks base method
func (m *MockProcessingContextInterface) CurrentlyProcessing(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentlyProcessing", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CurrentlyProcessing indicates an expected call of CurrentlyProcessing
func (mr *MockProcessingContextInterfaceMockRecorder) CurrentlyProcessing(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentlyProcessing", reflect.TypeOf((*MockProcessingContextInterface)(nil).CurrentlyProcessing), name)
}

// ProcessingComplete mocks base method
func (m *MockProcessingContextInterface) ProcessingComplete(name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessingComplete", name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessingComplete indicates an expected call of ProcessingComplete
func (mr *MockProcessingContextInterfaceMockRecorder) ProcessingComplete(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessingComplete", reflect.TypeOf((*MockProcessingContextInterface)(nil).ProcessingComplete), name)
}

// IncrementRecordsProcessed mocks base method
func (m *MockProcessingContextInterface) IncrementRecordsProcessed(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRecordsProcessed", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRecordsProcessed indicates an expected call of IncrementRecordsProcessed
func (mr *MockProcessingContextInterfaceMockRecorder) IncrementRecordsProcessed(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRecordsProcessed", reflect.TypeOf((*MockProcessingContextInterface)(nil).IncrementRecordsProcessed), name)
}

// SetNumRecords mocks base method
func (m *MockProcessingContextInterface) SetNumRecords(name string, num int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNumRecords", name, num)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNumRecords indicates an expected call of SetNumRecords
func (mr *MockProcessingContextInterfaceMockRecorder) SetNumRecords(name, num interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNumRecords", reflect.TypeOf((*MockProcessingContextInterface)(nil).SetNumRecords), name, num)
}

// NumCurrentlyProcessing mocks base method
func (m *MockProcessingContextInterface) NumCurrentlyProcessing() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumCurrentlyProcessing")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumCurrentlyProcessing indicates an expected call of NumCurrentlyProcessing
func (mr *MockProcessingContextInterfaceMockRecorder) NumCurrentlyProcessing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumCurrentlyProcessing", reflect.TypeOf((*MockProcessingContextInterface)(nil).NumCurrentlyProcessing))
}
